# Generated by Django 2.2.2 on 2020-06-09 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(upload_to='TaskForce/category_images/', verbose_name='Заставка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('canceled', 'Закрыто'), ('in_word', 'В работе'), ('completed', 'Выполнено'), ('failed', 'Провалено')], default='new', max_length=100, verbose_name='Статус')),
                ('location', models.CharField(choices=[('moscow', 'Москва'), ('moscow_region', 'МО'), ('st-Petersburg', 'Санкт-Петербург'), ('krasnodar', 'Краснодар'), ('irkutsk', 'Иркутск'), ('vladivostok', 'Владивосток')], max_length=100, verbose_name='Локация')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Бюджет')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('period_of_execution', models.DateField(verbose_name='Срок исполнения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='TaskForce.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='TaskForce/tasks/', verbose_name='Загруженные файлы')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskForce.Task', verbose_name='У задачи')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
            },
        ),
    ]
