# Generated by Django 2.2.2 on 2020-06-11 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TaskForce', '0004_task_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='applications',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Заявки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='worker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
