# Generated by Django 2.2.2 on 2020-06-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskForce', '0008_auto_20200611_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='application',
            name='text',
            field=models.CharField(default='Я хочу выполнить задание!', max_length=255),
        ),
    ]
